package:
    name: cylp
    version: 0.7.2

source:
    git_url: https://github.com/mpy/CyLP
    git_tag: 0.7.2


build:
    number: 1

requirements:
    build:
        - python
        - numpy
        - cbc

    run:
        - python
        - numpy
        - cbc

test:
    imports:
        - cylp

about:
    home: https://github.com/mpy/CyLP
    license: Common Public License Version 1.0
